travis:
  secure:
    BINSTAR_TOKEN: D3mnZFt7PbAf4P28UqkK/va18JIn2aM7dGl0X3frii07INUOeBh+V6mx4RPpf/2GHRO0Jv419xtROnnTeLls1+kInbO56gpYlcg3gUGsnLodBAJb7/7rXbWstfjBZ+3UvRQldJExD0dAtjGVtEe4ITiupghYsyp4SApI9jWdxAlyRIxsVccAIuh0JzRgVQCmEZqLEQu8WotvEEcOMj+ngHLgMCgZv4FbJ3lF+HT5Wu4L+mgapLgGuyY+rtQ285YML0eG7THm8pZAHIj9o7upcJFhFJn38ZbrZeTBwp2TX5AmDMvO5+KWq8mCR62uf4xbGGlfBvBPz8vveOSdj9r3dCB86lQaMoOhRjuPtW/c1zF3BcaQoD3t5Pn22/9dWA4ANhFV0y1VJhABJT/8OhAdX0AJj2EjNfTpgUxXItff4OQTR0FG/l0vLuADQ2fq5I+l3zWUWms0BoRjjO3Pp6AUFtDgnksVQ7st6IdnNDYabHd46D6PGQ+HTpgRgmDK2Go8BxZl5Zl3vLFiqjsVIGoY4m6SRt6Lq/9bEoGepaASOUJ5qWILs3f98nsOg7zqMgU/1uJUtwa9qFe/YE9dC/eMAqEt47KUqV0PeXmmNZzKWYWI80DXWL8duBCskFgV9MuQVNLMVvWwEzi2Vbf2uosynJzo1MY85eUcCipIuqa9w00=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
